# TLS listener
listener 8883

# Certificates
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/broker.crt
keyfile /mosquitto/certs/broker.key

# Require client certificate (mTLS)
require_certificate true

# Use CN as username
use_identity_as_username true

# Security
allow_anonymous false

# Logging
log_type all
